version: '3.8'

services:
  email-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
